### ISSUE TITLE
Check if Oculus runtime is installed

### ISSUE THREAD

**Issue by gmpreussner** [InnerLoopLLC/OculusPlatformBP#2]
How is this plug-in supposed to work if the Oculus runtime is not installed? The way it is currently implemented, a number of OVR functions are always executed on module load if the plug-in is enabled (via the CDOs). However, on PCs that do not have the Oculus runtime installed, this will straight up crash, because the OVR lib will fail to delay-load the required runtime DLLs.

I think that the plug-in code may have to be refactored to check whether Oculus platform initialization succeeded, and only then call functions in the platform SDK.

**Comment by ItsNotMeTrustMe** [comment]
Oh, great catch! Thanks for pointing that out. Embarrassingly, I had overlooked that in a few places. It should be solved in the new version which I just pushed.

**Comment by ItsNotMeTrustMe** [comment]
Closing this issue as I believe it has been resolved. Let me know if you're still experiencing any problems. Thanks!
