### ISSUE TITLE
Crash on app start

### ISSUE THREAD

**Issue by oferbaharav** [InnerLoopLLC/OculusPlatformBP#3]
I followed the instructions in the readme to update the engine with Oculus Platform SDK v27, we are using Oculus Engine 4.25.4 https://github.com/Oculus-VR/UnrealEngine/tree/oculus-4.25.4-release-1.55.0-v23.0, and configured your plugin in our project. It crashes on app start, with nothing showing in the logs. Would it matter that now if the headset is now on Oculus Platform SDK v28? Do any other dependencies need to be updated in the engine, or can you think of anything else we might try? I can try updating your plugin to v28, looks like there are only a couple new things deprecated. We're specifically trying to implement IAP.

**Comment by ItsNotMeTrustMe** [comment]
When building for Oculus Quest, please make sure that you've taken the step to add the _AndroidSettings.ini_ file and configured it properly. Without that file present, the Oculus Platform SDK will cause a crash on app load.

1) In your project's config folder, alongside your _DefaultEngine.ini_ file, create a new folder called _Android_. 
2) Within that folder, create the file _AndroidSettings.ini_. 
3) That file should include the following lines: (without quotes)

"[OnlineSubsystem]
DefaultPlatformService=Oculus"

Please let me know if this helps!

**Comment by ItsNotMeTrustMe** [comment]
As for your other questions, there are no additional dependencies which need to be updated. And there should be no issue using v28 or any other version of the Oculus Platform SDK. The plugin handles whichever version of the SDK is installed (v1.24 or later). The functions deprecated in v28 shouldn't cause an issue, as they should fail silently when those nodes are used. 

The plugin will be updated for v28 soon, but there are no major changes in that version.

**Comment by ItsNotMeTrustMe** [comment]
Well, actually... my fault. There was a bug in the plugin code which would cause a crash on anything above v19. The last update was meant to address that crash, but I missed one fix in that update... 🤦 I'll be pushing another update soon, which should solve this problem.

**Comment by oferbaharav** [comment]
Thank you, yes that worked. The file name seems to be AndroidEngine.ini not AndroidSettings.ini. We had overlooked that in the documentation when we set this up many weeks ago so this definitely helped. It didn't crash though until updating the SDK and using

The reason we switched to your plugin was in an attempt to get IAP to work - been trying for weeks now.

We are running the Oculus Developer Hub app and the Oculus app, logged in to our developer account.

We still have the same issues however, as follows.

When we do a build we see this in the console output:
```
UATHelper: Packaging (Android (ASTC)): GetSignatureToken get_signature error: Missing entitlement for <our app id>(1971031)
PackagingResults: Error: Missing entitlement for <our app id> (1971031)
UATHelper: Packaging (Android (ASTC)): requestOafRoomUpdate response error: Must call get_signature first (1971051)
UATHelper: Packaging (Android (ASTC)): requestOafLaunchDetailsUpdate response error: Must call get_signature first (1971051)
PackagingResults: Error: Must call get_signature first (1971051)
PackagingResults: Error: Must call get_signature first (1971051)

```
And we think related to that when we try to trigger an IAP using the Oculus/Launch Checkout Flow node we get:

```
"Cannot Purchase Additional Content"
"<our app name here> is required to purchase Monthly Subscription."
"OK"
```

We do verify entitlement in the app in BP_GameInstanceMain on app start using the Oculus/Entitlement/Verify Entitlement node and it is successful.

and in DefaultEngine.ini we have:
```
[OnlineSubsystem]
DefaultPlatformService=Oculus
bHasVoiceEnable=true

[OnlineSubsystemOculus]
bEnabled=true
OculusAppId=<our app id>
```

So far nobody at Oculus support or or developer relations contact has been able to shed any light on this. Seems like you're an experienced Oculus developer, have you seen anything like this and know how to fix it? 

Oh, one last question. There is a file in the sdk directory, Windows\OVR_PlatformLoader.cpp, that your readme doesn't mention if it needs to be copied over or not, and there was not such a file originally in our Engine source. I've tried recompiling the engine both with and without this, it doesn't seem to make any difference for us at least. Should it be copied over into the Engine source too?

Thanks.

**Comment by ItsNotMeTrustMe** [comment]
Awesome! I'm glad that helped get it working. I'll have a new version up shortly which should solve the crash with the updated SDK.

> The file name seems to be AndroidEngine.ini not AndroidSettings.ini

Ah! You're totally correct. I was responding from memory and mixed up the name. I'm glad you got that sorted out.

> We do verify entitlement in the app in BP_GameInstanceMain on app start using the Oculus/Entitlement/Verify Entitlement node and it is successful.

A potential issue which may arise is that Event Init in the game instance may sometimes fire prior to OnlineSubsystemOculus being loaded. To prevent this, I'd recommend either delaying the entitlement check somehow or calling it on Begin Play in a blueprint actor. Though, if your current setup is working, then it should be fine.

> There is a file in the sdk directory, Windows\OVR_PlatformLoader.cpp

This file is already present in _Engine\Plugins\Online\OnlineSubsystemOculus\Source\Private_ and, as far as I'm aware, hasn't been changed in quite some time. There should be no reason to update this file at the moment.

Regarding the other stuff, I haven't actually configured IAP in my projects, so I'm not 100% sure it all works as expected. But I have some thoughts. Have you previously uploaded a build to an Oculus release channel? And have you added your Oculus email to that release channel? If not, then you may want to try doing that. It sounds like entitlement is not actually passing successfully, even though you're passing the entitlement check.

**Comment by ItsNotMeTrustMe** [comment]
Ok, the fix for using an updated Oculus Platform SDK is now live. That should get you back to just trying to make IAP work. Let me know if my suggestion above helps at all on that front.

**Comment by ItsNotMeTrustMe** [comment]
Oh! The other thing to check, regarding IAP, is that you've completed the Data Use Checkup for this app on the Oculus Developer site. You'll need to submit this for each platform feature you intend to use. 

https://developer.oculus.com/manage/applications/[your-app-id]/data-use-checkup/

**Comment by oferbaharav** [comment]
Thanks for the tips. Yes we completed the Data Use checkup, the Event Init firing before OnlineSubystemOculus being loaded sounds promising. I looked more and it turns out that OVR_PlatformLoader.cpp is substantially different, about 2k bigger than what's there, it's because we're on 4.25.4 Oculus Engine branch, which turns out is/was on Platform SDK v23. It seems a big leap to v27 or v28, my guess is the OnlineSubsystemOculus isn't even loading properly now . The 4.26 branch is on Platform SDK v28, I've being going down the rabbit hole of trying to backport that to 4.25.4 but not going well so far. Might be easier to update our project to 4.26, dunno yet...

**Comment by ItsNotMeTrustMe** [comment]
Looking at the [compatibility matrix](https://developer.oculus.com/documentation/unreal/unreal-compatibility-matrix/), the Platform SDK version is the same for both 4.25.4 and 4.26.2. Platform SDK v20 (1.52).

To make my life easier while updating this plugin, I maintain a private repo that just has each SDK in it. That way I can easily diff each version and see everything that has changed. _OVR_PlatformLoader.cpp_ was last modified in Platform SDK v25... but essentially the only change is to the formatting. They just removed a ton of white space. In a practical sense, that file hasn't changed at all in a very long time. Feel free to update it, but I would be quite surprised if that solved the issue.

Would you mind emailing your UE4 logs and _DefaultEngine.ini_ so I can take a closer look? Please send logs to brian@superhockeyball.com. Or feel free to join my [Discord server](https://discord.gg/AxxpQ8h) where I can assist in real time.

To get the UE4 logs from a Quest project, make a Quest package in development configuration (because logs aren't created in shipping config unless you've modified the engine to do so). Then run your game on Quest to generate logs. Finally, execute the following adb command to pull the UE4 logs from the device:
`adb pull /storage/emulated/0/Android/data/com.[your_company].[your_project]/files/UE4Game/[your_project]/[your_project]/Saved/Logs`

One more question: Have you configured your app on the Oculus developer site as a Quest (App Lab) project? If you're using the same AppID as a Rift app, that will not work, as your app would always fail entitlement for platform services.

**Comment by ItsNotMeTrustMe** [comment]
Closing this as the main issue with IAP doesn't appear to be a problem with the plugin, and the rest of the questions have been addressed in the updated README. If you need further help, please contact me via email/Discord or re-open the issue.
